export const site = {
  name: "Electronic Artefacts",
  origin: "https://electronicartefacts.com",
  description: "Electronic Artefacts designs digital products, knowledge systems, cultural platforms and research-led experiences.",
  updatedAt: "2026-06-25",
  locale: "en_US",
  language: "en",
  publisherId: "ea:organization:electronic-artefacts",
  socialImage: "/assets/media/projects/electronic-artefacts/electronic-artefacts-search.jpg",
  logoImage: "/assets/media/projects/electronic-artefacts/electronic-artefacts-logo.jpg",
  contactEmail: "electronic.artefacts@gmail.com",
  keywords: [
    "creative technology",
    "knowledge graph",
    "AI agents",
    "retrieval-augmented generation",
    "linked data",
    "digital preservation",
    "cultural infrastructure",
    "software systems",
    "research publishing",
  ],
  knowsAbout: [
    "AI agents",
    "knowledge graphs",
    "retrieval-augmented generation",
    "linked data",
    "JSON-LD",
    "creative coding",
    "digital preservation",
    "cultural knowledge systems",
    "software architecture",
    "human-computer interaction",
    "generative AI",
    "provenance",
  ],
  sameAs: [
    "https://www.instagram.com/electronic.artefacts/",
    "https://github.com/onlythejoe",
    "https://soundcloud.com/electronic-artefacts",
  ],
} as const;
