import { defaultLocale, localeConfig } from "./i18n.js";

export const site = {
  name: "Electronic Artefacts",
  alternateNames: ["electronicArtefacts", "electronicartefacts.com"],
  origin: "https://electronicartefacts.com",
  description: "Electronic Artefacts is an independent creative technology studio for complex digital products, knowledge systems, proprietary software and research-led cultural work.",
  updatedAt: "2026-07-08",
  locale: localeConfig(defaultLocale).ogLocale,
  language: defaultLocale,
  publisherId: "ea:organization:electronic-artefacts",
  socialImage: "/assets/media/projects/electronic-artefacts/electronic-artefacts-search.jpg",
  logoImage: "/assets/media/projects/electronic-artefacts/electronic-artefacts-logo.jpg",
  contactEmail: "electronic.artefacts@gmail.com",
  keywords: [
    "creative technology",
    "digital product strategy",
    "UX design",
    "web development",
    "knowledge graph",
    "AI agents",
    "retrieval-augmented generation",
    "linked data",
    "digital preservation",
    "cultural infrastructure",
    "software systems",
    "research publishing",
  ],
  knowsAbout: [
    "AI agents",
    "knowledge graphs",
    "retrieval-augmented generation",
    "linked data",
    "JSON-LD",
    "creative coding",
    "digital preservation",
    "cultural knowledge systems",
    "software architecture",
    "human-computer interaction",
    "generative AI",
    "provenance",
  ],
  sameAs: [
    "https://www.instagram.com/electronic.artefacts/",
    "https://github.com/onlythejoe",
    "https://soundcloud.com/electronic-artefacts",
  ],
} as const;
