window.EA_ACTIVITY = [
  {
    id: "activity-001",
    type: "program_milestone",
    title: "VASTE milestone reached",
    entityId: "vaste",
    date: "2026-06-12",
    summary: "Public site settles into place.",
  },
  {
    id: "activity-002",
    type: "artifact_published",
    title: "Audio artefacts published",
    entityId: "palimpsests",
    date: "2026-06-12",
    summary: "Entropy, Emergence and related fragments surfaced.",
  },
  {
    id: "activity-003",
    type: "research_updated",
    title: "Research fields updated",
    entityId: "entropy",
    date: "2026-06-12",
    summary: "Entropy and signal archaeology gained new material.",
  },
  {
    id: "activity-004",
    type: "research_updated",
    title: "V6 platform definition aligned",
    entityId: "vestiges",
    date: "2026-06-22",
    summary: "Future V6 mapping and CRM research context documented.",
  },
  {
    id: "activity-005",
    type: "channel_updated",
    title: "CreativeStuff.jpg updated",
    entityId: "creativestuff",
    date: "2026-06-12",
    summary: "Visual references and studies expanded.",
  },
];
