window.EA_RELATIONS = {
  graph: [
    { from: "electronic-artefacts", to: "vaste", type: "Powered By" },
    { from: "electronic-artefacts", to: "oreth", type: "Produced By" },
    { from: "electronic-artefacts", to: "electronic-artefacts-website", type: "Produced By" },
    { from: "electronic-artefacts", to: "null-underscore-human", type: "Produced By" },
    { from: "electronic-artefacts", to: "oeil-de-meg-crm", type: "Produced By" },
    { from: "electronic-artefacts", to: "oeil-de-meg-plugin", type: "Produced By" },
    { from: "electronic-artefacts", to: "oeil-de-meg-theme", type: "Produced By" },
    { from: "electronic-artefacts", to: "oeil-de-meg-pinterest-sync", type: "Produced By" },
    { from: "electronic-artefacts", to: "oeil-de-meg-gallery-system", type: "Produced By" },
    { from: "electronic-artefacts", to: "oeil-de-meg-calendar", type: "Produced By" },
    { from: "electronic-artefacts", to: "palimpsests", type: "Part Of" },
    { from: "electronic-artefacts", to: "vestiges", type: "Part Of" },
    { from: "electronic-artefacts", to: "voice-capture-studio", type: "Produced By" },
    { from: "vestiges", to: "vaste", type: "Powered By" },
    { from: "voice-capture-studio", to: "oreth-program", type: "Related To" },
    { from: "electronic-artefacts", to: "creativestuff", type: "Related To" },
    { from: "palimpsests", to: "entropy-audio", type: "Part Of" },
    { from: "palimpsests", to: "emergence-audio", type: "Part Of" },
    { from: "palimpsests", to: "palimpsest-audio", type: "Part Of" },
    { from: "palimpsests", to: "incandescence-audio", type: "Part Of" },
    { from: "palimpsests", to: "keraunos-audio", type: "Part Of" },
    { from: "palimpsests", to: "etoiles-audio", type: "Part Of" },
    { from: "palimpsests", to: "experiences-audio", type: "Part Of" },
    { from: "palimpsests", to: "nerve-corrupted", type: "Part Of" },
    { from: "palimpsests", to: "soft-control-audio", type: "Part Of" },
    { from: "palimpsests", to: "out-of-memory-audio", type: "Part Of" },
    { from: "palimpsests", to: "crash-audio", type: "Part Of" },
    { from: "palimpsests", to: "resilience-audio", type: "Part Of" },
  ],
  relationTypes: [
    "Origin",
    "Parent",
    "Children",
    "Dependencies",
    "Influences",
    "Derived From",
    "Inspired By",
    "Powered By",
    "Produced By",
    "Published By",
    "Maintained By",
    "Part Of",
    "Related To",
  ],
};
