window.EA_TAXONOMIES = {
  temporality: {
    foundation: { label: "Foundation" },
    emergence: { label: "Emergence" },
    palimpsests: { label: "Palimpsests" },
    vestiges: { label: "V6" },
  },
  maturity: {
    concept: { label: "Concept" },
    research: { label: "Research" },
    prototype: { label: "Prototype" },
    experimental: { label: "Experimental" },
    development: { label: "Development" },
    production: { label: "Production" },
    released: { label: "Released" },
    archived: { label: "Archived" },
    deprecated: { label: "Deprecated" },
  },
  confidence: {
    speculative: { label: "Speculative" },
    observed: { label: "Observed" },
    validated: { label: "Validated" },
    published: { label: "Published" },
    canonical: { label: "Canonical" },
  },
  visibility: {
    public: { label: "Public" },
    internal: { label: "Internal" },
    archive: { label: "Archive" },
    restricted: { label: "Restricted" },
  },
  statuses: {
    concept: { label: "Concept", className: "status-badge--concept", icon: "◌" },
    research: { label: "Research", className: "status-badge--research", icon: "◌" },
    experimental: { label: "Experimental", className: "status-badge--experimental", icon: "◎" },
    prototype: { label: "Prototype", className: "status-badge--prototype", icon: "◍" },
    development: { label: "Development", className: "status-badge--development", icon: "◐" },
    production: { label: "Production", className: "status-badge--production", icon: "●" },
    released: { label: "Released", className: "status-badge--released", icon: "◉" },
    active: { label: "Active", className: "status-badge--active", icon: "●" },
    archived: { label: "Archived", className: "status-badge--archived", icon: "⌁" },
    deprecated: { label: "Deprecated", className: "status-badge--archived", icon: "⌁" },
  },
  entityTypes: {
    program: "PROGRAM",
    project: "PROJECT",
    artist: "ARTIST",
    artefact: "ARTEFACT",
    channel: "CHANNEL",
    researchField: "RESEARCH FIELD",
    researchLog: "RESEARCH LOG",
    collection: "COLLECTION",
    document: "DOCUMENT",
    visual: "VISUAL",
    audio: "AUDIO",
    prototype: "PROTOTYPE",
    archive: "ARCHIVE",
    universe: "UNIVERSE",
    lore: "LORE",
    narrative: "NARRATIVE",
    mythology: "MYTHOLOGY",
    civilisation: "CIVILISATION",
    location: "LOCATION",
    concept: "CONCEPT",
    phenomenon: "PHENOMENON",
  },
  mediums: [
    "Audio",
    "Visual",
    "Photography",
    "Software",
    "Runtime",
    "Research",
    "Writing",
    "Film",
    "Installation",
    "Interactive",
    "Performance",
  ],
  disciplines: [
    "Music",
    "Technology",
    "Design",
    "Art Direction",
    "Branding",
    "Research",
    "Systems",
    "Narrative",
    "Worldbuilding",
    "Photography",
    "Architecture",
    "UX",
    "UI",
    "Development",
  ],
  projectCategories: [
    "Album",
    "Platform",
    "Universe",
    "Client Work",
    "External Collaboration",
    "Research Initiative",
    "Software",
    "Framework",
    "Runtime",
    "Publication",
    "Tool",
  ],
  relationshipTags: [
    "Origin",
    "Parent",
    "Children",
    "Dependencies",
    "Influences",
    "Derived From",
    "Inspired By",
    "Powered By",
    "Produced By",
    "Published By",
    "Maintained By",
    "Part Of",
    "Related To",
  ],
};
