import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const cssSources = [
  "assets/css/tokens.css",
  "assets/css/base.css",
  "assets/css/layout.css",
  "assets/css/typography.css",
  "assets/css/components.css",
  "assets/css/cards.css",
  "assets/css/style.css",
];

const jsSources = [
  "assets/js/data/taxonomies.js",
  "assets/js/data/entities.js",
  "assets/js/data/relations.js",
  "assets/js/data/timelines.js",
  "assets/js/data/activity.js",
  "assets/js/data/collections.js",
  "assets/js/data/search-index.js",
  "assets/js/catalog.js",
  "assets/js/core/utils.js",
  "assets/js/core/includes.js",
  "assets/js/core/ui.js",
  "assets/js/core/view.js",
  "assets/js/core/surface.js",
  "assets/js/core/behaviors.js",
  "assets/js/main.js",
];

const bundle = async (sources, destination, banner) => {
  const chunks = [banner];
  for (const source of sources) {
    const absolutePath = path.join(rootDir, source);
    const content = await readFile(absolutePath, "utf8");
    chunks.push(`/* ==== ${source} ==== */\n${content.trimEnd()}`);
  }

  const targetPath = path.join(rootDir, destination);
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, `${chunks.join("\n\n")}\n`);
};

await bundle(cssSources, "assets/css/app.css", "/* Generated by scripts/build-assets.mjs. Edit the source CSS files instead. */");
await bundle(jsSources, "assets/js/app.js", "/* Generated by scripts/build-assets.mjs. Edit the source JS files instead. */");

process.stdout.write("Built assets/css/app.css and assets/js/app.js\n");
