import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const cssSources = [
  "assets/css/tokens.css",
  "assets/css/base.css",
  "assets/css/layout.css",
  "assets/css/typography.css",
  "assets/css/components.css",
  "assets/css/cards.css",
  "assets/css/style.css",
];

const dataSources = [
  "assets/js/data/taxonomies.js",
  "assets/js/data/entities.js",
  "assets/js/data/relations.js",
  "assets/js/data/timelines.js",
  "assets/js/data/activity.js",
  "assets/js/data/collections.js",
];

const jsSources = [
  "assets/js/data/search-index.js",
  "assets/js/catalog.js",
  "assets/js/core/utils.js",
  "assets/js/core/includes.js",
  "assets/js/core/i18n.js",
  "assets/js/core/analytics-config.js",
  "assets/js/core/analytics.js",
  "assets/js/core/ui.js",
  "assets/js/core/view.js",
  "assets/js/core/surface.js",
  "assets/js/core/behaviors.js",
  "assets/js/main.js",
];

const buildPublicData = async () => {
  const context = vm.createContext({ window: {} });
  let collectionRuntime = "";
  for (const source of dataSources) {
    const content = await readFile(path.join(rootDir, source), "utf8");
    vm.runInContext(content, context, { filename: source });
    if (source.endsWith("collections.js")) {
      const runtimeStart = content.indexOf("const resolvedCollectionCache");
      if (runtimeStart >= 0) collectionRuntime = content.slice(runtimeStart).trim();
    }
  }

  const entities = context.window.EA_ENTITIES || {};
  const collections = context.window.EA_COLLECTIONS || [];
  const isPublic = (item) => !["internal", "restricted"].includes(item?.visibility);
  const publicEntities = Object.fromEntries(
    Object.entries(entities).map(([key, items]) => [key, Array.isArray(items) ? items.filter(isPublic) : items]),
  );
  const publicCollections = collections.filter(isPublic);
  const allSourceEntities = [...Object.values(entities).filter(Array.isArray).flat(), ...collections];
  const privateIds = new Set(allSourceEntities.filter((item) => !isPublic(item)).map((item) => item.id).filter(Boolean));

  const removePrivateReferences = (value) => {
    if (Array.isArray(value)) {
      return value
        .filter((item) => typeof item !== "string" || !privateIds.has(item))
        .map(removePrivateReferences);
    }
    if (!value || typeof value !== "object") return value;
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, removePrivateReferences(item)]));
  };

  const relations = context.window.EA_RELATIONS || {};
  const publicRelations = {
    ...relations,
    graph: (relations.graph || []).filter((edge) => !privateIds.has(edge.from) && !privateIds.has(edge.to)),
  };
  const publicTimelines = (context.window.EA_TIMELINES || []).filter((item) => !privateIds.has(item.entityId));
  const publicActivity = (context.window.EA_ACTIVITY || []).filter((item) => !privateIds.has(item.entityId));

  const assignments = [
    ["EA_TAXONOMIES", context.window.EA_TAXONOMIES || {}],
    ["EA_ENTITIES", removePrivateReferences(publicEntities)],
    ["EA_RELATIONS", removePrivateReferences(publicRelations)],
    ["EA_TIMELINES", removePrivateReferences(publicTimelines)],
    ["EA_ACTIVITY", removePrivateReferences(publicActivity)],
    ["EA_COLLECTIONS", removePrivateReferences(publicCollections)],
  ];

  return {
    assignments: assignments
      .map(([name, value]) => `window.${name} = ${JSON.stringify(value, null, 2)};`)
      .join("\n\n"),
    collectionRuntime,
  };
};

const bundle = async (sources, destination, banner) => {
  const chunks = [banner];
  for (const source of sources) {
    const absolutePath = path.join(rootDir, source);
    const content = await readFile(absolutePath, "utf8");
    chunks.push(`/* ==== ${source} ==== */\n${content.trimEnd()}`);
  }

  const targetPath = path.join(rootDir, destination);
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, `${chunks.join("\n\n")}\n`);
};

await bundle(cssSources, "assets/css/app.css", "/* Generated by scripts/build-assets.mjs. Edit the source CSS files instead. */");
const publicData = await buildPublicData();
let generatedCatalog = null;
try {
  generatedCatalog = JSON.parse(await readFile(path.join(rootDir, "generated/public/catalog.json"), "utf8"));
} catch {
  generatedCatalog = null;
}
const jsBanner = "/* Generated by scripts/build-assets.mjs. Edit the source JS files instead. */";
const jsChunks = [
  jsBanner,
  "/* Public data: internal and restricted records are excluded at build time. */",
  publicData.assignments,
  publicData.collectionRuntime,
  generatedCatalog ? `window.EA_PUBLIC_CATALOG = ${JSON.stringify(generatedCatalog, null, 2)};` : "",
];
for (const source of jsSources) {
  const content = await readFile(path.join(rootDir, source), "utf8");
  jsChunks.push(`/* ==== ${source} ==== */\n${content.trimEnd()}`);
}
await writeFile(path.join(rootDir, "assets/js/app.js"), `${jsChunks.join("\n\n")}\n`);

process.stdout.write("Built assets/css/app.css and assets/js/app.js\n");
