import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { transform } from "esbuild";
import { PurgeCSS } from "purgecss";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const cssSources = [
  "assets/css/tokens.css",
  "assets/css/base.css",
  "assets/css/layout.css",
  "assets/css/typography.css",
  "assets/css/components.css",
  "assets/css/cards.css",
  "assets/css/style.css",
];

const legacyDataSources = [
  "src/legacy-data/taxonomies.js",
  "src/legacy-data/entities.js",
  "src/legacy-data/relations.js",
  "src/legacy-data/timelines.js",
  "src/legacy-data/activity.js",
  "src/legacy-data/collections.js",
];

const jsSources = [
  "src/legacy-data/search-index.js",
  "assets/js/catalog.js",
  "assets/js/core/utils.js",
  "assets/js/core/includes.js",
  "assets/js/core/i18n.js",
  "assets/js/core/ui.js",
  "assets/js/core/view.js",
  "assets/js/core/surface.js",
  "assets/js/core/behaviors.js",
  "assets/js/core/context-menu.js",
  "assets/js/main.js",
];

const flowSource = "assets/js/core/flow.js";

const buildPublicData = async () => {
  const context = vm.createContext({ window: {} });
  let collectionRuntime = "";
  for (const source of legacyDataSources) {
    const content = await readFile(path.join(rootDir, source), "utf8");
    vm.runInContext(content, context, { filename: source });
    if (source.endsWith("collections.js")) {
      const runtimeStart = content.indexOf("const resolvedCollectionCache");
      if (runtimeStart >= 0) collectionRuntime = content.slice(runtimeStart).trim();
    }
  }

  const entities = context.window.EA_ENTITIES || {};
  const collections = context.window.EA_COLLECTIONS || [];
  const isPublic = (item) => !["internal", "restricted"].includes(item?.visibility);
  const publicEntities = Object.fromEntries(
    Object.entries(entities).map(([key, items]) => [key, Array.isArray(items) ? items.filter(isPublic) : items]),
  );
  const publicCollections = collections.filter(isPublic);
  const allSourceEntities = [...Object.values(entities).filter(Array.isArray).flat(), ...collections];
  const privateIds = new Set(allSourceEntities.filter((item) => !isPublic(item)).map((item) => item.id).filter(Boolean));

  const removePrivateReferences = (value) => {
    if (Array.isArray(value)) {
      return value
        .filter((item) => typeof item !== "string" || !privateIds.has(item))
        .map(removePrivateReferences);
    }
    if (!value || typeof value !== "object") return value;
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, removePrivateReferences(item)]));
  };

  const relations = context.window.EA_RELATIONS || {};
  const publicRelations = {
    ...relations,
    graph: (relations.graph || []).filter((edge) => !privateIds.has(edge.from) && !privateIds.has(edge.to)),
  };
  const publicTimelines = (context.window.EA_TIMELINES || []).filter((item) => !privateIds.has(item.entityId));
  const publicActivity = (context.window.EA_ACTIVITY || []).filter((item) => !privateIds.has(item.entityId));

  const assignments = [
    ["EA_TAXONOMIES", context.window.EA_TAXONOMIES || {}],
    ["EA_ENTITIES", removePrivateReferences(publicEntities)],
    ["EA_RELATIONS", removePrivateReferences(publicRelations)],
    ["EA_TIMELINES", removePrivateReferences(publicTimelines)],
    ["EA_ACTIVITY", removePrivateReferences(publicActivity)],
    ["EA_COLLECTIONS", removePrivateReferences(publicCollections)],
  ];

  return {
    assignments: assignments
      .map(([name, value]) => `window.${name} = ${JSON.stringify(value, null, 2)};`)
      .join("\n\n"),
    collectionRuntime,
  };
};

const minify = async (source, loader) => (await transform(source, {
  legalComments: "none",
  loader,
  minify: true,
  target: "es2020",
})).code;

const bundle = async (sources, destination, banner, loader) => {
  const chunks = [banner];
  for (const source of sources) {
    const absolutePath = path.join(rootDir, source);
    const content = await readFile(absolutePath, "utf8");
    chunks.push(`/* ==== ${source} ==== */\n${content.trimEnd()}`);
  }

  const targetPath = path.join(rootDir, destination);
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, await minify(`${chunks.join("\n\n")}\n`, loader));
};

await bundle(cssSources, "assets/css/app.css", "/* Generated by scripts/build-assets.mjs. Edit the source CSS files instead. */", "css");
await bundle(
  ["assets/js/core/analytics-config.js", "assets/js/core/analytics.js"],
  "assets/js/analytics.js",
  "/* Generated consent and analytics runtime. */",
  "js",
);
const publishedCssPath = path.join(rootDir, "assets/css/app.css");
const [purgedCss] = await new PurgeCSS().purge({
  content: [
    "*.html", "fr/**/*.html", "projects/**/*.html", "programs/**/*.html", "knowledge/**/*.html",
    "publications/**/*.html", "research/**/*.html", "archive/**/*.html", "organizations/**/*.html",
    "src/templates/**/*.ts", "assets/js/catalog.js", "assets/js/main.js", "assets/js/core/*.js",
  ].map((pattern) => path.join(rootDir, pattern)),
  css: [publishedCssPath],
  safelist: { greedy: [/\.(?:is|has|was|no)-/, /\.is-safari/, /active-view-transition/] },
});
await writeFile(publishedCssPath, await minify(purgedCss.css, "css"));
const [homeCss] = await new PurgeCSS().purge({
  content: ["index.html", "fr/index.html", "assets/partials/header.html", "assets/partials/footer.html", flowSource]
    .map((file) => path.join(rootDir, file)),
  css: [publishedCssPath],
  safelist: { greedy: [/\.(?:is|has|was|no)-/, /\.is-safari/, /active-view-transition/] },
});
await writeFile(path.join(rootDir, "assets/css/home.css"), await minify(homeCss.css, "css"));
const [projectCss] = await new PurgeCSS().purge({
  content: ["projects/**/*.html", "fr/projects/**/*.html", "assets/partials/header.html", "assets/partials/footer.html"]
    .map((pattern) => path.join(rootDir, pattern)),
  css: [publishedCssPath],
  safelist: { greedy: [/\.(?:is|has|was|no)-/, /\.is-safari/, /active-view-transition/] },
});
await writeFile(path.join(rootDir, "assets/css/project.css"), await minify(projectCss.css, "css"));
await bundle([flowSource], "assets/js/flow.js", "/* Generated critical navigation and loading runtime. */", "js");
const publicData = await buildPublicData();
let generatedCatalog = null;
try {
  generatedCatalog = JSON.parse(await readFile(path.join(rootDir, "generated/public/catalog.json"), "utf8"));
} catch {
  generatedCatalog = null;
}
const runtimeEntityKeys = [
  "id", "legacyId", "translationOf", "locale", "kind", "type", "title", "subtitle", "summary",
  "status", "maturity", "confidence", "visibility", "publicationClass", "tags", "discipline", "route",
  "identifier", "temporality", "homepage", "priority", "started", "abstract",
];
const fullRuntimeCatalog = generatedCatalog ? {
  schemaVersion: generatedCatalog.schemaVersion,
  entities: (generatedCatalog.entities || []).map((entity) => Object.fromEntries(
    runtimeEntityKeys.filter((key) => entity[key] !== undefined).map((key) => [key, entity[key]]),
  )),
  relations: (generatedCatalog.relations || []).map(({ id, subject, predicate, object }) => ({ id, subject, predicate, object })),
  routes: generatedCatalog.routes || {},
} : null;
const runtimeCatalog = fullRuntimeCatalog ? {
  ...fullRuntimeCatalog,
  entities: fullRuntimeCatalog.entities.filter((entity) => entity.type === "researchQuestion"),
  relations: [],
} : null;
const jsBanner = "/* Generated by scripts/build-assets.mjs. Edit the source JS files instead. */";
const embeddedIncludes = Object.fromEntries(
  await Promise.all(
    ["header", "footer"].map(async (key) => [
      key,
      (await readFile(path.join(rootDir, `assets/partials/${key}.html`), "utf8")).trim(),
    ]),
  ),
);
const runtimeChunks = [];
for (const source of jsSources) {
  const content = await readFile(path.join(rootDir, source), "utf8");
  runtimeChunks.push(`/* ==== ${source} ==== */\n${content.trimEnd()}`);
}
const writeRuntime = async (destination, catalog) => {
  const chunks = [
    jsBanner,
    "/* Public data: internal and restricted records are excluded at build time. */",
    publicData.assignments,
    publicData.collectionRuntime,
    catalog ? `window.EA_PUBLIC_CATALOG = ${JSON.stringify(catalog)};` : "",
    `window.EA_EMBEDDED_INCLUDES = ${JSON.stringify(embeddedIncludes)};`,
    ...runtimeChunks,
  ];
  await writeFile(path.join(rootDir, destination), await minify(`${chunks.join("\n\n")}\n`, "js"));
};

await Promise.all([
  writeRuntime("assets/js/app.js", runtimeCatalog),
  writeRuntime("assets/js/app-full.js", fullRuntimeCatalog),
]);

process.stdout.write("Built minified CSS and route-scoped JavaScript bundles\n");
